name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRES_MINUTES: ${{ secrets.JWT_EXPIRES_MINUTES }}
          envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          envkey_MAIL_FROM: ${{ secrets.MAIL_FROM }}
          envkey_MAIL_PORT: ${{ secrets.MAIL_PORT }}
          envkey_MAIL_HOST: ${{ secrets.MAIL_HOST }}

      - name: Build Docker images
        run: |
          docker build . -t api-todo-app-v2:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove old container
        run: |
          docker rm --force api-todo-app-v2

      - name: run new container
        run: |
          docker run -d --restart unless-stopped --name api-todo-app-v2 -p 2200:8000 api-todo-app-v2:${{ github.sha }}
